///This file is automatically generated. DO NOT EDIT, all your changes would be lost.
class Assets {
  Assets._();

  static const String followUpsJson = 'assets/jsons/followups.json';
  static const String noDataImage = 'assets/images/no_data.png';
}
